; --- Fichier généré automatiquement par script Python ---
; Source : assets/images/aseprite/kris_bedroom_atlas.json

SPRITE_FRAME_SIZE equ 12 ; (6 valeurs * 2 octets)

; --- Constantes d'index --- 
KRIS_BEDROOM_FURNITURES_0 equ 0
KRIS_BEDROOM_FURNITURES_1 equ 1
KRIS_BEDROOM_FURNITURES_2 equ 2
KRIS_BEDROOM_FURNITURES_3 equ 3
KRIS_BEDROOM_FURNITURES_4 equ 4
KRIS_BEDROOM_FURNITURES_5 equ 5
KRIS_BEDROOM_FURNITURES_6 equ 6
KRIS_BEDROOM_FURNITURES_7 equ 7
KRIS_BEDROOM_FURNITURES_8 equ 8
KRIS_BEDROOM_FURNITURES_9 equ 9
KRIS_BEDROOM_FURNITURES_10 equ 10
KRIS_BEDROOM_FURNITURES_11 equ 11
KRIS_BEDROOM_FURNITURES_12 equ 12
KRIS_BEDROOM_FURNITURES_13 equ 13
KRIS_BEDROOM_FURNITURES_14 equ 14
KRIS_BEDROOM_FURNITURES_15 equ 15
KRIS_BEDROOM_FURNITURES_16 equ 16
KRIS_BEDROOM_FURNITURES_17 equ 17
KRIS_BEDROOM_FURNITURES_18 equ 18
KRIS_BEDROOM_FURNITURES_19 equ 19
KRIS_BEDROOM_FURNITURES_20 equ 20
KRIS_BEDROOM_FURNITURES_21 equ 21
KRIS_BEDROOM_FURNITURES_22 equ 22
KRIS_BEDROOM_FURNITURES_23 equ 23
KRIS_BEDROOM_FURNITURES_24 equ 24
KRIS_BEDROOM_FURNITURES_25 equ 25
KRIS_BEDROOM_FURNITURES_26 equ 26
KRIS_BEDROOM_FURNITURES_27 equ 27

section .rodata
global kris_bedroom_atlas

kris_bedroom_atlas:
    ; Index 0: kris_bedroom_furnitures 0
    db 0, 0, 75, 46, 0, 2

    ; Index 1: kris_bedroom_furnitures 1
    db 92, 71, 35, 42, 75, 32

    ; Index 2: kris_bedroom_furnitures 2
    db 125, 2, 2, 2, 75, 42

    ; Index 3: kris_bedroom_furnitures 3
    db 123, 4, 1, 1, 77, 43

    ; Index 4: kris_bedroom_furnitures 4
    db 121, 4, 2, 2, 78, 42

    ; Index 5: kris_bedroom_furnitures 5
    db 125, 0, 3, 2, 75, 44

    ; Index 6: kris_bedroom_furnitures 6
    db 127, 2, 1, 2, 79, 44

    ; Index 7: kris_bedroom_furnitures 7
    db 121, 0, 4, 4, 80, 42

    ; Index 8: kris_bedroom_furnitures 8
    db 64, 46, 10, 18, 94, 42

    ; Index 9: kris_bedroom_furnitures 9
    db 45, 71, 47, 34, 0, 46

    ; Index 10: kris_bedroom_furnitures 10
    db 45, 105, 47, 34, 47, 46

    ; Index 11: kris_bedroom_furnitures 11
    db 12, 152, 16, 11, 94, 60

    ; Index 12: kris_bedroom_furnitures 12
    db 98, 137, 19, 23, 0, 80

    ; Index 13: kris_bedroom_furnitures 13
    db 0, 139, 49, 13, 19, 80

    ; Index 14: kris_bedroom_furnitures 14
    db 117, 151, 8, 9, 19, 93

    ; Index 15: kris_bedroom_furnitures 15
    db 117, 143, 11, 8, 27, 93

    ; Index 16: kris_bedroom_furnitures 16
    db 0, 132, 13, 7, 38, 93

    ; Index 17: kris_bedroom_furnitures 17
    db 49, 139, 49, 13, 68, 80

    ; Index 18: kris_bedroom_furnitures 18
    db 0, 152, 12, 16, 117, 85

    ; Index 19: kris_bedroom_furnitures 19
    db 28, 152, 12, 13, 129, 87

    ; Index 20: kris_bedroom_furnitures 20
    db 0, 117, 22, 15, 141, 87

    ; Index 21: kris_bedroom_furnitures 21
    db 45, 46, 19, 24, 163, 71

    ; Index 22: kris_bedroom_furnitures 22
    db 92, 113, 19, 24, 182, 71

    ; Index 23: kris_bedroom_furnitures 23
    db 22, 117, 18, 15, 145, 71

    ; Index 24: kris_bedroom_furnitures 24
    db 111, 113, 15, 16, 130, 71

    ; Index 25: kris_bedroom_furnitures 25
    db 117, 129, 9, 14, 117, 71

    ; Index 26: kris_bedroom_furnitures 26
    db 0, 46, 45, 71, 110, 104

    ; Index 27: kris_bedroom_furnitures 27
    db 75, 0, 46, 71, 155, 102

